# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/T490/pointblankattempt/pointblankattempt.srcs/sources_1/ip/shelf_bram/shelf_bram.xci
# IP: The module: 'shelf_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/T490/pointblankattempt/pointblankattempt.srcs/sources_1/ip/shelf_bram/shelf_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'shelf_bram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/T490/pointblankattempt/pointblankattempt.srcs/sources_1/ip/shelf_bram/shelf_bram.xci
# IP: The module: 'shelf_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/T490/pointblankattempt/pointblankattempt.srcs/sources_1/ip/shelf_bram/shelf_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'shelf_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
